# Generated by Django 3.1.5 on 2021-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0013_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
