# Generated by Django 3.1.5 on 2021-05-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0016_auto_20210508_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
