# Generated by Django 3.1.5 on 2021-05-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0005_wishlist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='pic_path',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='publishdate',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='web',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookMng.book'),
        ),
    ]
