# Generated by Django 3.1.5 on 2021-05-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0006_auto_20210430_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='username',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookMng.book'),
        ),
    ]
