# Generated by Django 3.1.5 on 2021-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0007_auto_20210502_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='book',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(to='bookMng.Book'),
        ),
    ]
