# Generated by Django 3.1.5 on 2021-05-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0010_auto_20210502_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
