# Generated by Django 3.1.5 on 2021-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0019_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='card',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
