# Generated by Django 3.1.5 on 2021-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0020_auto_20210510_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
