# Generated by Django 3.1.5 on 2021-05-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0021_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
    ]
