# Generated by Django 3.1.5 on 2021-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0022_remove_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pic_path',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
    ]
