# Generated by Django 3.1.5 on 2021-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0023_cart_pic_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='picture',
            field=models.FileField(null=True, upload_to='bookEx/static/uploads'),
        ),
    ]
